{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "scancentral-sast-controller.fullname" . }}
spec:
  serviceName: {{ include "scancentral-sast-controller.fullname" . }}
  selector:
    matchLabels:
      component: controller
      {{- include "scancentral-sast.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if not .Values.secrets.secretName }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
      {{- if .Values.trustedCertificates }}
        checksum/trusted-certificates: {{ include (print $.Template.BasePath "/certs-configmap.yaml") . | sha256sum }}
      {{- end }}
      {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: controller
        {{- include "scancentral-sast.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        # must be kept in sync with image metadata
        runAsUser: 1111
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            - name: SCANCENTRAL_CONFIG_WORKER_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "scancentral-sast-secret.fullname" . }}
                  key: scancentral-worker-auth-token
            - name: SCANCENTRAL_CONFIG_CLIENT_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "scancentral-sast-secret.fullname" . }}
                  key: scancentral-client-auth-token
            - name: SCANCENTRAL_CONFIG_SSC_SCANCENTRAL_CTRL_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "scancentral-sast-secret.fullname" . }}
                  key: scancentral-ssc-scancentral-ctrl-secret
            - name: SCANCENTRAL_CONFIG_SSC_URL
              value: {{ .Values.controller.sscUrl | quote }}
            - name: SCANCENTRAL_CONFIG_SSC_REMOTE_IP
              value: {{ .Values.controller.sscRemoteIp | quote }}
            {{- if .Values.controller.thisUrl }}
            - name: SCANCENTRAL_CONFIG_THIS_URL
              value: {{ .Values.controller.thisUrl | quote }}
            {{- end }}
            {{- if .Values.trustedCertificates }}
            - name: SCANCENTRAL_CONFIG_TRUSTED_CERTS_DIR
              value: "/trusted-certificates"
            {{- end }}
            {{- with .Values.controller.additionalEnvironment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: controller-data
              mountPath: "/fortify"
            {{- if .Values.trustedCertificates }}
            - name: trusted-certificates
              mountPath: "/trusted-certificates"
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /scancentral-ctrl/
              port: http
          readinessProbe:
            # Wait at least 1 minute for migration tasks
            initialDelaySeconds: 30
            httpGet:
              path: /scancentral-ctrl/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: controller-data
          {{- if .Values.controller.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.controller.persistence.existingClaim | default (printf "data-%s" (include "scancentral-sast-controller.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.trustedCertificates }}
        - name: trusted-certificates
          configMap:
            name: {{ include "scancentral-sast-certificates.fullname" . }}
        {{- end }}
      nodeSelector:
      {{- with .Values.controller.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.controller.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
