{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scancentral-sast-controller.fullname" . }}
  labels:
    component: controller
    {{- include "scancentral-sast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: controller
    {{- include "scancentral-sast.selectorLabels" . | nindent 4 }}
{{- end }}
